fieldLayouts:
  9b46e212-f160-4794-9ddc-c99a0552eb19:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: d80ade78-a242-43cf-9553-e36e969a687a
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: ea09fb40-148e-4724-aadc-8ea407ba803d # Bio
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 29e7699b-b575-49f4-8229-0f760c7490ba
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: a01140c9-933c-4615-9456-d5225f516e07 # Profile Photo
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 98f47563-dca1-4c07-a618-3008f702022f
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 47904234-ba8a-45e9-beea-1eb24526f237
        userCondition: null
handle: about
hasTitleField: false
name: About
section: 559d46b4-0ece-4728-8ca9-41605fde40b2 # About
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
sortOrder: 1
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
