fieldLayouts:
  4fcea703-c6db-4abf-b4db-7450fb00927f:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: c68eeb4c-6d6c-41b5-ad73-9a5d1b82e5b9
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 378a371d-c4f6-456a-924d-a9093d3a7128
        userCondition: null
fs: hardDisk
handle: images
name: Images
sortOrder: 1
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: ''
transformSubpath: ''
