columnSuffix: null
contentColumnType: string
fieldGroup: c188ac46-2f1f-465b-8a22-35bf275de680 # Common
handle: postContent
instructions: null
name: 'Post Content'
searchable: false
settings:
  contentTable: '{{%matrixcontent_postcontent}}'
  maxBlocks: null
  minBlocks: null
  propagationKeyFormat: null
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
