columnSuffix: shqhqzcr
contentColumnType: text
fieldGroup: c188ac46-2f1f-465b-8a22-35bf275de680 # Common
handle: summary
instructions: 'Summaries should be one or two sentences.'
name: Summary
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: false
  columnType: null
  initialRows: 1
  multiline: true
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
